package ro.mpp2024.network.jsonprotocol;

public enum ResponseType {
    OK, ERROR, GET_GROUPS, GET_CONTESTS_AND_PARTICIPATION_COUNT_BY_GROUP, GET_CONTESTANTS_AND_PARTICIPATION_COUNT_BY_CONTEST, ADD_CONTESTANT, GET_GROUP_BY_AGE, GET_CONTESTS_BY_GROUP, ADD_PARTICIPATION, LOGIN, PARTICIPATION_NOTIFICATION;
}
